// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"github.com/x-debug/Go-000/Week04/internal/biz"
	"github.com/x-debug/Go-000/Week04/internal/data"
)

// Injectors from wire.go:

func CreateUserCase() *biz.UserCase {
	db := data.NewDB()
	userDao := data.NewUserDao(db)
	userCase := biz.NewUserCase(userDao)
	return userCase
}
