// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/x-debug/Go-000/Week04/internal/biz"
	"github.com/x-debug/Go-000/Week04/internal/data"
)

// Injectors from wire.go:

func InitializeDB() (*data.DBConn, func(), error) {
	dbConf := data.NewConf()
	dbConn, cleanup := data.NewDB(dbConf)
	return dbConn, func() {
		cleanup()
	}, nil
}

func createUserCase() (*biz.UserCase, func(), error) {
	dbConf := data.NewConf()
	dbConn, cleanup := data.NewDB(dbConf)
	userDao := data.NewUserDao(dbConn)
	userCase := biz.NewUserCase(userDao)
	return userCase, func() {
		cleanup()
	}, nil
}

// wire.go:

var dbProviders = wire.NewSet(data.NewDB, data.NewConf)

func GetUserCase() *biz.UserCase {
	userCase, _, _ := createUserCase()
	return userCase
}
